# Generated by Django 5.0.6 on 2024-12-23 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsSignUp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='stripe_product_id',
        ),
        migrations.AddField(
            model_name='league',
            name='stripe_product',
            field=models.ForeignKey(blank=True, help_text='Stripe product associated with this league', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues', to='sportsSignUp.stripeproduct'),
        ),
    ]
