# Generated by Django 5.0.6 on 2024-11-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsSignUp', '0002_stripeproduct_stripeprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeprice',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
