# Generated by Django 5.0.6 on 2024-11-30 20:25

import django.db.models.deletion
import sportsSignUp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsSignUp', '0003_stripeprice_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='registration_type',
        ),
        migrations.RemoveField(
            model_name='team',
            name='captains',
        ),
        migrations.AddField(
            model_name='team',
            name='team_logo',
            field=models.FileField(blank=True, null=True, upload_to='team_logos/'),
        ),
        migrations.CreateModel(
            name='TeamCaptain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_system_captain', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_captains', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(default=sportsSignUp.models.TeamCaptain.get_default_captain, on_delete=django.db.models.deletion.PROTECT, related_name='captained_teams', to='sportsSignUp.teamcaptain'),
        ),
    ]
