# Generated by Django 5.0.6 on 2024-11-30 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsSignUp', '0004_remove_registration_registration_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_logo',
        ),
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captained_teams', to='sportsSignUp.teamcaptain'),
        ),
    ]
