# Generated by Django 5.0.6 on 2024-11-30 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsSignUp', '0005_remove_team_team_logo_alter_team_captain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='stripe_product_id',
        ),
        migrations.AddField(
            model_name='league',
            name='stripe_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leagues', to='sportsSignUp.stripeproduct'),
        ),
    ]
