# Generated by Django 5.0.6 on 2024-11-30 21:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsSignUp', '0006_remove_league_stripe_product_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='league',
            name='stripe_product',
        ),
        migrations.AddField(
            model_name='league',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(default='defaultemail@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='membership_number',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='parent_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='phone_number',
            field=models.CharField(default=8675309, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_logo',
            field=models.FileField(blank=True, null=True, upload_to='team_logos/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
