# Generated by Django 5.0.6 on 2024-11-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsSignUp', '0007_alter_player_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='membership_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
