# Generated by Django 5.0.6 on 2024-11-30 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsSignUp', '0009_remove_player_jersey_number_remove_player_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_logo',
        ),
    ]
