# Generated by Django 5.0.6 on 2024-12-08 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsSignUp', '0013_custom_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='signup_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='FreeAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('parent_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('membership_number', models.CharField(max_length=100)),
                ('is_member', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('INVITED', 'Invited'), ('JOINED', 'Joined')], default='AVAILABLE', max_length=10)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsSignUp.division')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsSignUp.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('free_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsSignUp.freeagent')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsSignUp.team')),
            ],
        ),
    ]
