# Generated by Django 5.0.6 on 2024-12-09 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsSignUp', '0014_alter_team_signup_code_freeagent_teaminvitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='freeagent',
            unique_together={('user', 'league')},
        ),
        migrations.AlterField(
            model_name='freeagent',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_agents', to='sportsSignUp.division'),
        ),
        migrations.AlterField(
            model_name='freeagent',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_agents', to='sportsSignUp.league'),
        ),
        migrations.AlterField(
            model_name='freeagent',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('INVITED', 'Invited'), ('JOINED', 'Joined'), ('INACTIVE', 'Inactive')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='freeagent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_agent_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='freeagent',
            name='parent_name',
        ),
    ]
