# Generated by Django 5.0.6 on 2024-12-10 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsSignUp', '0015_alter_freeagent_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvitation',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='free_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='sportsSignUp.freeagent'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='sportsSignUp.team'),
        ),
        migrations.AlterUniqueTogether(
            name='teaminvitation',
            unique_together={('team', 'free_agent')},
        ),
    ]
