# Generated by Django 5.0.6 on 2024-12-10 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsSignUp', '0016_teaminvitation_message_teaminvitation_response_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInvitationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sportsSignUp.teaminvitation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
