# Generated by Django 5.0.6 on 2024-12-15 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill_level', models.CharField(blank=True, max_length=50)),
                ('age_group', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_start_date', models.DateField()),
                ('registration_end_date', models.DateField()),
                ('early_registration_deadline', models.DateField()),
                ('league_start_date', models.DateField()),
                ('league_end_date', models.DateField()),
                ('regular_registration_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('early_registration_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('max_teams', models.IntegerField(blank=True, null=True)),
                ('available_divisions', models.ManyToManyField(limit_choices_to={'sport': models.F('sport')}, related_name='league_sessions', to='leagues.division')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='leagues.sport')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='leagues.sport'),
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together={('name', 'sport')},
        ),
    ]
